
[log]
level = "trace"

[dbs]
redis = "redis://127.0.0.1:6379/2"
#redisRead = "redis://127.0.0.1:6379/2"
#redisWrite = "redis://127.0.0.1:6379/2"

[api]
enabled = true
workers = 2
port = 5080
host = "127.0.0.1"

[dns]
enabled = true
workers = 2
port = 5053
host = "127.0.0.1"
ttl = 300 # 5 min


[[ns]]
    # first NS is also reported as the master in SOA record
    domain = "testdns01.pendingdns.com"
    ip = "188.165.168.22"
[[ns]]
    domain = "testdns02.pendingdns.com"
    ip = "51.38.177.242"

[soa]
    admin = "hostmaster.pendingdns.com"
    serial = 2020050501
    refresh = 3600
    retry = 600
    expiration = 604800
    minimum = 60

[resolver]
    ns = ["8.8.8.8", "1.1.1.1"]

[acme]
    # Local identifier for the ACME account
    key = "postaldns"
    # Defaults to Let's Encrypt staging environment
    directoryUrl = "https://acme-staging-v02.api.letsencrypt.org/directory"
    
    # Email address to recive account related notifications
    # This value must be set as this is the person who agrees to LE TOS
    email = ""